---
version: "2.14"
services:
  api:
    build:
      context: ./rest
    container_name: api
    environment:
      - DATABASE_URL=mongodb://mongodb:27017
    ports:
      - "3001:3001"
    restart: unless-stopped
    volumes:
      - ./rest:/usr/src/app
    depends_on:
      - mongodb
    networks:
      - dev
  
  graphql:
    build:
      context: ./graphql
    container_name: graphql
    environment:
      - BACKEND_API_URL=http://api:3001
    ports:
      - "3002:3002"
    restart: unless-stopped
    volumes:
      - ./graphql:/usr/src/app
    depends_on:
      - api
    networks:
      - dev
  
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    networks:
      - dev
networks:
  dev:
    driver: bridge
